title: WebApp Using Github Pages
author: kiranlpatil.cs@gmail.com
description: >-
  An informative blog for learning SOLID Principles in simple wordings

# theme: minima
remote_theme: pages-themes/cayman@v0.2.0

plugins:
#  - jekyll-feed
  - jekyll-remote-theme


github:
  is_project_page: false
